host: localhost:3002
protocol: http
port: 3002
ca_location: certs/ca.crt
cert_location: certs/server.crt
key_location: certs/server.key
backend_servers:
  - http://localhost:8080
  - http://localhost:8081
waf:
  allowedIPs:
      - 10.0.0.0/8 #0.0.0.0/0 10.0.0.0/8
      - 192.168.1.0/24
      - 172.16.0.0/12
      - 127.0.0.1
  allowedPorts:
      - 80
      - 443
      - "*"

