host: localhost:3002
protocol: http
port: 3002
ca_location: server.crt
cert_location: server.crt
key_location: server.key
backend_servers:
  - http://localhost:8080
  - http://localhost:8081
waf:
  allowedIPs:
      - 10.0.0.0/8 #0.0.0.0/0 10.0.0.0/8
      - 192.168.1.0/24
      - 172.16.0.0/12
      - 127.0.0.1
  allowedPorts:
      - 80
      - 443
      - "*"
  additionalRequestHeaders:
      - X-Forwarded-For: ""
  additionalResponseHeaders:
      - wallet-hash: "dGVzdFZhbHVlMTIzwiefhw02-urWREFWrg"
      - X-Frame-Options: "DENY"
