host: localhost:3002
protocol: http
port: 80
cert_location: server.crt
key_location: server.key
backend_servers:
  - http://localhost:8080
  - http://localhost:8081
waf:
  - allowedIPs:
      - 127.0.0.1 #10.0.0.0/8
      - 192.168.1/24
      - 172.16.0/12
      - 127.0.0.1
  - denyIPs:
      - 192.168.2/24
      - 10.1.0/16
      - 172.17.0/16
